# Generated by Django 5.1.6 on 2025-05-28 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0002_etudiant_user_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='classe_responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='responsable_filiere.classe'),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='g3nnilJWkzcU2lgqm0nuH05VKA1RWw5Q', editable=False, max_length=32, unique=True),
        ),
    ]
