# Generated by Django 5.1.6 on 2025-05-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0002_etudiant_classe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('heure_de_debut', models.TimeField()),
                ('heure_de_fin', models.TimeField()),
                ('type_evenement', models.CharField(choices=[('examen', 'Examen'), ('atelier', 'Atelier'), ('reunion', 'Réunion')], max_length=50)),
                ('classes_concernees', models.ManyToManyField(to='responsable_filiere.classe')),
            ],
        ),
    ]
