# Generated by Django 5.1.6 on 2025-05-24 00:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0003_evenement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examen',
            name='classe',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='date',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='heure_de_debut',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='heure_de_fin',
        ),
        migrations.RemoveField(
            model_name='examen',
            name='type_examen',
        ),
        migrations.AddField(
            model_name='examen',
            name='evenement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='responsable_filiere.evenement'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='titre',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='type_evenement',
            field=models.CharField(choices=[('examen', 'Examen'), ('projet', 'Projet'), ('reunion', 'Réunion'), ('autre', 'Autre')], default='examen', max_length=50),
        ),
        migrations.AlterField(
            model_name='examen',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsable_filiere.matiere'),
        ),
    ]
