# Generated by Django 5.1.6 on 2025-05-28 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0003_customuser_classe_responsable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_responsable_adjoint',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='PUpKqNkB7u9pBzmGZzzEtUb5IGZbwpw7', editable=False, max_length=32, unique=True),
        ),
    ]
