# Generated by Django 5.1.6 on 2025-05-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0004_customuser_is_responsable_adjoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='credits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='volume_horaire',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='4WLT1LChTrmPR3bNxEvKaJTxcQZkvtFu', editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='EmploiDuTemps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=10)),
                ('horaire', models.CharField(choices=[('08:00 - 10:00', 'P1'), ('10:15 - 12:15', 'P2'), ('14:30 - 16:30', 'P3'), ('16:45 - 18:45', 'P4')], max_length=20)),
                ('matiere', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsable_filiere.classe')),
            ],
        ),
    ]
