# Generated by Django 5.1.6 on 2025-05-28 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0006_alter_passwordresetrequest_token_seance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gpSYKYGiROrWSvFhNrYamda5xVuTU6vH', editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_absence', models.CharField(choices=[('non_justifiee', 'Absence injustifiée'), ('justifiee', 'Absence justifiée'), ('retard', 'Retard'), ('maladie', 'Maladie')], max_length=50)),
                ('justification', models.TextField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsable_filiere.etudiant')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responsable_filiere.seance')),
            ],
        ),
    ]
