# Generated by Django 5.1.6 on 2025-05-28 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responsable_filiere', '0007_alter_passwordresetrequest_token_absence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='8Aia0yIS8XydwQpQcdQN1ztxgIPeUGNb', editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('travail', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateField(auto_now_add=True)),
                ('seance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecon', to='responsable_filiere.seance')),
            ],
        ),
    ]
